### ISSUE TITLE
CREATE COMPONENT 

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/landing_page_reactJS_collab#2]
To complete this task you need to: 

- [x] Create folder name **Components** in the **src** folder 
- [x] Delete all the necessary files which comes with the create-react-app command 
- [x] Create three files in the **Components** folder named: Header.jsx, Main.jsx and Footer.jsx 
- [x] Create one **style.css** file in the Components folder which will contain all css properties for all of the three .jsx files

**Comment by nedimmujcinovic** [comment]
Take a look at my code...
