### ISSUE TITLE
Create boilerplate in every .jsx files

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/landing_page_reactJS_collab#4]
To complete this you will need to: 

- [x] create boilerplate in every .jsx files. 
- [x] in every .jsx file write h1 title "name of the file"
- [x] after that you will import all of these files in the main.jsx file 
- [x] after that import only main.jsx file in the App.js file 

If you finished all of these steps correctly, you will have on the display showing: 

Header
Main
Footer

**Comment by nedimmujcinovic** [comment]
I created and test all files after imports in App.js

**Comment by DenisKantic** [comment]
You have completed all the task. Great work !
